name: trainer_app
description: WTF Trainer App for Trainers (Aarav Persona)
version: 1.0.0
publish_to: 'none'

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.2
  intl: ^0.19.0
  uuid: ^4.3.3
  http: ^1.2.0
  path_provider: ^2.1.2
  shared_preferences: ^2.2.2
  hmssdk_flutter: ^1.11.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
